# Generated by Django 5.2.4 on 2025-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizations",
            name="account_manager",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizations",
            name="activation_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizations",
            name="cnpj",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="organizations",
            name="iatec_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizations",
            name="propz_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizations",
            name="status_r_flag",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizations",
            name="zoox_flag",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
