# Generated by Django 5.2.4 on 2025-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0002_organizations_account_manager_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("meraki_id", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=14, null=True)),
                ("account_manager", models.CharField(max_length=100, null=True)),
                ("activation_flag", models.BooleanField(max_length=100, null=True)),
                ("zoox_flag", models.BooleanField(max_length=100, null=True)),
                ("propz_flag", models.BooleanField(max_length=100, null=True)),
                ("iatec_flag", models.BooleanField(max_length=100, null=True)),
                ("status_report_flag", models.BooleanField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Organizations",
        ),
    ]
