# Generated by Django 5.2.4 on 2025-07-22 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0003_organization_delete_organizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("serial", models.CharField(max_length=100, null=True)),
                ("mac_address", models.CharField(max_length=100, null=True)),
                ("local", models.CharField(max_length=100, null=True)),
                ("admin", models.CharField(max_length=100, null=True)),
                ("activation_flag", models.BooleanField(null=True)),
                ("license", models.CharField(null=True)),
                ("days_until_expiration", models.IntegerField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_org",
                        to="devices_monitor.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_product",
                        to="devices_monitor.product",
                    ),
                ),
            ],
        ),
    ]
