# Generated by Django 5.2.4 on 2025-07-22 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0004_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="device_category",
                to="devices_monitor.category",
            ),
        ),
    ]
