# Generated by Django 5.2.4 on 2025-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0007_device_category_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
