# Generated by Django 5.2.4 on 2025-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0009_alter_device_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="category",
            field=models.CharField(default="categoria"),
        ),
    ]
