# Generated by Django 5.2.4 on 2025-07-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0010_alter_device_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="category",
        ),
    ]
