# Generated by Django 5.2.4 on 2025-07-22 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0012_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="device_category",
                to="devices_monitor.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="device",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
