# Generated by Django 5.2.4 on 2025-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0013_device_category_alter_category_id_alter_device_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mac_address",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
