# Generated by Django 5.2.4 on 2025-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0014_alter_device_mac_address_alter_device_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="license",
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="activation_flag",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="cnpj",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="iatec_flag",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="propz_flag",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="status_report_flag",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="zoox_flag",
            field=models.BooleanField(null=True),
        ),
    ]
