# Generated by Django 5.2.4 on 2025-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0015_alter_device_license_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="cnpj",
            field=models.CharField(default="Sem cnpj", max_length=14, unique=True),
        ),
    ]
