# Generated by Django 5.2.4 on 2025-07-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0017_alter_organization_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="cnpj",
            field=models.CharField(default="Vazio", max_length=14, unique=True),
        ),
    ]
