# Generated by Django 5.2.3 on 2025-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0018_alter_organization_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="license",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
