# Generated by Django 5.2.3 on 2025-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_monitor", "0019_alter_device_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="meraki_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
